@echo off

set PROJ_NAME=EP4CE10

echo create new folder
set/a time_h=%time:~0,2%+100
set/a real_h=%time_h%-100
if %real_h% GTR 9 (
    set/a time_m=%time:~3,2%+100
) else (
    set/a time_m=%time:~2,2%+100
)
set folder=%PROJ_NAME%_%date:~0,4%%date:~5,2%%date:~8,2%_%time_h:~1,2%%time_m:~1,2%

md ..\"%folder%"

echo copy project file
cd ..\"%folder%"
xcopy /y /s ..\%PROJ_NAME%\DESIGN.sim   .\DESIGN.sim\
xcopy /y /s ..\%PROJ_NAME%\DESIGN.srcs  .\DESIGN.srcs\
xcopy /y /s ..\%PROJ_NAME%\DESIGN.tcl   .\DESIGN.tcl\
xcopy /y /s ..\%PROJ_NAME%\DESIGN.qpf   .\
xcopy /y /s ..\%PROJ_NAME%\DESIGN.qsf   .\

echo //generated by run.bat     >> .\DESIGN.srcs\sources_1\TCL_DEFINE.vh

copy /b .\DESIGN.qsf + .\DESIGN.tcl\set_run.tcl + .\DESIGN.srcs\constrs_1\IO.tcl
